version: '3.9'

services:
  davi-backend:
    container_name: davi-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile-dev
    volumes:
      - ./backend:/app
    ports:
      - "5001:5000"
  davi-frontend:
    container_name: davi-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile-dev
    ports:
      - "8081:8080"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  davi-nginx:
    container_name: davi-nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
        - "81:80"
    depends_on:
    - davi-frontend
    - davi-backend
